[project]
name = "zerohertz-reflex"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "reflex>=0.6.8",
    "xlrd>=2.0.1",
    "zerohertzlib[api]>=1.1.9",
]
